"""Adicionando campos created_at e update_at no todos- Corrigido

Revision ID: 7bd8fe5cb92e
Revises: b2caf1bd3398
Create Date: 2025-06-15 16:24:05.404204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd8fe5cb92e'
down_revision: Union[str, None] = 'b2caf1bd3398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
       batch_op.add_column(
           sa.Column(
               'created_at', 
               sa.DateTime(), 
               server_default=sa.text('(CURRENT_TIMESTAMP)'), 
               nullable=False
            )
       )
       batch_op.add_column(
           sa.Column(
               'updated_at', 
               sa.DateTime(), 
               server_default=sa.text('(CURRENT_TIMESTAMP)'), 
               nullable=False
            )
       )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
       batch_op.drop_column('updated_at')
       batch_op.drop_column('created_at')
    # ### end Alembic commands ###
